# Generated by Django 5.1.6 on 2025-03-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_remove_productsnapshot_review_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsnapshot',
            name='delta_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='productsnapshot',
            name='delta_rating',
            field=models.CharField(default='0', help_text='Rating difference from previous snapshot', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='productsnapshot',
            name='delta_review_count',
            field=models.IntegerField(default=0, help_text='Review count difference from previous snapshot', null=True),
        ),
        migrations.CreateModel(
            name='SEOKeywordTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_url', models.URLField()),
                ('top_seo_keywords', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['product_name'], name='tracking_se_product_e5832f_idx'), models.Index(fields=['created_at'], name='tracking_se_created_b9a169_idx')],
            },
        ),
    ]
