# Generated by Django 5.1.6 on 2025-03-03 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scrape', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price at the time of snapshot', max_digits=10)),
                ('rating', models.CharField(default='N/A', help_text='Product rating at the time of snapshot', max_length=10)),
                ('review_count', models.IntegerField(default=0, help_text='Number of product reviews at the time of snapshot')),
                ('delta_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price difference from previous snapshot', max_digits=10)),
                ('delta_rating', models.CharField(default='0', help_text='Rating difference from previous snapshot', max_length=10)),
                ('delta_review_count', models.IntegerField(default=0, help_text='Review count difference from previous snapshot')),
                ('captured_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when snapshot was taken')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='scrape.product')),
            ],
            options={
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['-captured_at'], name='tracking_pr_capture_7bbf3c_idx'), models.Index(fields=['product'], name='tracking_pr_product_da81d1_idx')],
            },
        ),
    ]
