# Generated by Django 5.1.6 on 2025-03-04 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0001_initial'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsnapshot',
            name='review_count',
        ),
        migrations.AddField(
            model_name='productsnapshot',
            name='reviews_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productsnapshot',
            name='delta_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productsnapshot',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productsnapshot',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrape.product'),
        ),
        migrations.AlterField(
            model_name='productsnapshot',
            name='rating',
            field=models.FloatField(),
        ),
    ]
