# Generated by Django 5.1.6 on 2025-03-24 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0001_initial'),
        ('tracking', '0003_alter_productsnapshot_delta_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seokeywordtracking',
            name='product_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='scrape.product'),
        ),
        migrations.AlterField(
            model_name='seokeywordtracking',
            name='top_seo_keywords',
            field=models.JSONField(default=list),
        ),
    ]
