# Generated by Django 5.1.6 on 2025-03-03 06:41

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of ecommerce website', max_length=500)),
                ('url', models.URLField(help_text='Amazon product URL', max_length=500, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of ecommerce website', max_length=500)),
                ('url', models.URLField(help_text='Amazon product URL', max_length=500, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name from Amazon', max_length=1500)),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('rating', models.CharField(default='N/A', help_text="Product rating (e.g., '4.5')", max_length=10)),
                ('review_count', models.IntegerField(default=0, help_text='Number of product reviews', validators=[django.core.validators.MinValueValidator(0)])),
                ('url', models.URLField(help_text='Amazon product URL', max_length=500, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='scrape_prod_created_d7b170_idx'), models.Index(fields=['price'], name='scrape_prod_price_12d689_idx')],
            },
        ),
    ]
